# For field details: https://amulet-docs.azurewebsites.net/config_file.html
description: Upload HF datasets

target:
  service: sing
  name: msrresrchvc #msrresrchvc #msrresrchlab
  workspace_name: bio0-ext

environment:
  image: base/job/pytorch/acpt-torch2.5.0-py3.10-cuda12.4-ubuntu22.04:20241022T103546977 #acpt-2.4.0-py3.10-cuda12.4:20240731T103952913
  registry: singularitybase.azurecr.io
  setup:
  - pip install pyfastx==2.2.0 datasets==3.2.0 huggingface-hub==0.27.1 python-dotenv==1.0.1 ijson==3.3.0 fsspec==2024.9.0 adlfs==2024.12.0

storage:
    output:
        storage_account_name: biomlcollab2
        container_name: dayhoffdata
        mount_dir: /mnt/my_outputs
        # mount_options: ["-o", "--file-cache-path=/mnt/my_outputs/mount_cache"]
    # data:
    #     storage_account_name: biomlcollab2
    #     container_name: dayhoffdata
    #     mount_dir: /mnt/my_data
  
code:
  local_dir: $CONFIG_DIR/ 

data: 
  #Location of the data relative to the container
  remote_dir: "." 

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
# - name: 'uniref50_202401' 
#   sku: G1 # 1 GPU Job
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fasta_path uniref50_202401/consensus.fasta --splits_path uniref50_202401/splits.json --dataset_type unclustered
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'uniref90_202401' 
#   sku: 8C30 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fasta_path uniref90_202401/consensus.fasta --splits_path uniref90_202401/clustered_splits.json --dataset_type clustered 
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'rfdiffusion' 
#   sku: 8C30 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fastas-glob-pattern "rfdiffusion/*.fasta" --dataset_type unclustered
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'dayhoffref' 
#   sku: 8C30 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fasta_path dayhoffref/dayhoffref.fasta --dataset_type unclustered
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_no_singletons' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fasta_path gigaref/consensus.fasta --split_names train test --splits_path gigaref/no_singletons/clustered_splits.json --dataset_type clustered --output_dir gigaref_no_singletons
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_with_singletons' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fasta_path gigaref/consensus.fasta --split_names train --splits_path gigaref/with_singletons/singletons.json --dataset_type unclustered --output_dir gigaref_with_singletons
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_all' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py --fasta_path gigaref/consensus.fasta --split_names train --splits_path gigaref/with_singletons/singletons.json --dataset_type unclustered --output_dir gigaref_with_singletons_v2
#   - python src/export-fasta.py --fasta_path gigaref/consensus.fasta --split_names train test --splits_path gigaref/no_singletons/clustered_splits.json --dataset_type clustered --output_dir gigaref_no_singletons_v2
#   submit_args:
#     env:
      # _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_no_singletons_v2_proc_4' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py
#     --fasta_path gigaref/consensus.fasta
#     --split_names train test
#     --splits_path gigaref/no_singletons/clustered_splits.json
#     --dataset_type clustered
#     --output_dir gigaref_no_singletons_v2
#     --num_proc 4
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_no_singletons_v3_proc_8' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py
#     --fasta_path gigaref/consensus.fasta
#     --split_names train test
#     --splits_path gigaref/no_singletons/clustered_splits.json
#     --dataset_type clustered
#     --output_dir gigaref_no_singletons_v3
#     --num_proc 8
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai





# - name: 'gigaref_no_singletons_v4_proc_16 set hf home' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py
#     --fasta_path gigaref/consensus.fasta
#     --split_names train test
#     --splits_path gigaref/no_singletons/clustered_splits.json
#     --dataset_type clustered
#     --output_dir gigaref_no_singletons_v4
#     --num_proc 16
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_no_singletons_v5_proc_32 set hf home' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py
#     --fasta_path gigaref/consensus.fasta
#     --split_names train test
#     --splits_path gigaref/no_singletons/clustered_splits.json
#     --dataset_type clustered
#     --output_dir gigaref_no_singletons_v5
#     --num_proc 32
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'gigaref_no_singletons_v4_proc_16 no caching' 
#   sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python src/export-fasta.py
#     --fasta_path gigaref/consensus.fasta
#     --split_names train test
#     --splits_path gigaref/no_singletons/clustered_splits.json
#     --dataset_type clustered
#     --output_dir gigaref_no_singletons_v4
#     --num_proc 16
#     --disable-caching
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai


- name: 'gigaref_no_singletons_v5_proc_32 no caching 10GB shards' 
  sku: 8C60 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
  priority: high
  identity: managed
  preemptible: False
  command:
  - python src/export-fasta.py
    --fasta_path gigaref/consensus.fasta
    --split_names train test
    --splits_path gigaref/no_singletons/clustered_splits.json
    --dataset_type clustered
    --output_dir gigaref_no_singletons_v6
    --num_proc 32
    --disable-caching
    --save-to-disk-max-shard-size "10GB"
    # --azure-storage-account-name biomlcollab2
    # --azure-storage-container-name dayhoffdata
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai



# - name: 'rfdiffusion test 5GB' 
#   sku: 8C7 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python
#     src/export-fasta.py
#     --fastas-glob-pattern "rfdiffusion/*filter.fasta"
#     --dataset_type unclustered
#     --output_dir samir_test_rf_diffusion_cpu
#     --num_proc 4
#     --disable-caching
#     --save-to-disk-max-shard-size "5GB"
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
# - name: 'rfdiffusion test without caching' 
#   sku: 8C7 # 1 GPU Job  8C15, 8C7, 8C30, 8C60
#   priority: high
#   identity: managed
#   preemptible: False
#   command:
#   - python
#     src/export-fasta.py
#     --fastas-glob-pattern "rfdiffusion/*filter.fasta"
#     --dataset_type unclustered
#     --output_dir samir_test_rf_diffusion_cpu
#     --num_proc 4
#     --disable-caching
#     # --azure-storage-account-name biomlcollab2
#     # --azure-storage-container-name dayhoffdata
#   submit_args:
#     env:
#       _AZUREML_SINGULARITY_JOB_UAI:  /subscriptions/7be94754-107d-43b8-b840-202dff0e7cae/resourceGroups/bio0-ext/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bio0-ext-uai
      





  